version: 1.0 # Version of the config file (DO NOT CHANGE THIS OR ELSE IT WILL REVERT TO DEFAULT)

server:
  hub_server: hub # The name of the hub server
  group_required: test # The group required to join the server
  database:
    use: remote # local or remote
    remote:
      host: localhost # The host of the database
      port: 3306 # The port of the database
      username: John # The username of the database
      password: doe123 # The password of the database
      schema: buildbattle # The schema of the database
    local:
      path: buildbattle.db # The path of the sqlite database
  scoreboard:
    network_name: "&dIES La Mola" # The name of the network
    server_name: TEST_1 # The name of the server
    server_ip: localhost # The ip of the server
  map:
    name: Test Map # The name of the map
    world: world # The name of the world
    min_players: 2 # The minimum players required to start the game
    win_event:
      positions: 3 # The positions that will be rewarded
      do:
        0:
          action: DB_RANKSET # The action to do
          value: Classified # The value of the action
    time: # The time of the game measured in seconds
      start: 60 # The time before the game starts
      game: 300 # The time before the game ends
      vote: 20 # The time of each vote
      end: 10 # The time before the server restarts
    build_zone: # The build zone of the map
      0:
        world: world # The world of the build zone
        spawn: # The spawn of the build zone (where the players will be teleported)
          x: 0
          y: 3
          z: 0
        spectator_spawn: # The spectator spawn of the build zone (the area where the players will be teleported when the game ends)
          x: 0
          y: 60
          z: 0
        floor: # The floor of the build zone (the area where the floor is)
          x: [ 0, 10 ]
          y: [ 2, 2 ]
          z: [ 0, 10 ]
        build: # The build area of the build zone (the area where the players can build)
          x: [ 0, 10 ]
          y: [ 2, 127 ]
          z: [ 0, 10 ]
      1:
        world: world
        spawn:
          x: 100
          y: 3
          z: 100
        spectator_spawn:
          x: 100
          y: 60
          z: 100
        floor:
          x: [ 100, 110 ]
          y: [ 2, 2 ]
          z: [ 100, 110 ]
        build:
          x: [ 100, 110 ]
          y: [ 2, 127 ]
          z: [ 100, 110 ]
    topics: [ "Selva", "Espada", "Guerra", "Caricatura", "Pelicula", "Cine", "Bombero", "Estacionamiento", "Restaurante", "Habitacion", "Pueblo", "Apocalipsis", "Carrera", "Pinguino", "Arbol", "Juguete", "Supermercado", "Biblioteca", "Retro", "Prehistoria", "Acuario", "Videojuego", "Infancia", "Medieval", "Cebra", "Elefante", "Universo", "Pascua", "Camara", "Edificio", "Experimento", "Ladron", "Pixelart", "Hot Dog", "Bandera", "Murcielago", "Unicorinio", "Teatro", "Guantes", "Vegetal", "Baño", "Parque de atracciones", "Astronauta", "Paleta", "Piramide" ]