name: BuildBattleTournament
version: 1.0
author: PK2_Stimpy
main: me.pk2.bbtournament.BuildBattleT
commands:
  bb-reload:
    description: Reloads the plugin
    aliases: [buildbattle-reload]
    usage: /bb-reload
  exit:
    description: Sends you to the lobby
    aliases: [lobby, hub]
    usage: /exit
  bbt:
    description: Main build battle command
    aliases: [buildbattletournament]
    usage: /bbt